### ISSUE TITLE
Missing link to GitHub in hex.m

### ISSUE THREAD

**Issue by vkatsuba** [etnt/etacacs_plus#3]
In hex.pm provided a https://hex.pm/packages/etacacs_plus link to documentation - but missed link to GitHub repo.

**Comment by etnt** [comment]
Hm...how do I specify that? I got this in the rebar.config file for the ex_doc plugin:

    {source_url, "https://github.com/etnt/etacacs_plus"}

**Comment by vkatsuba** [comment]
The source_url  is related only to ex_doc documentation only. I not sure I know what approach you use for push your project into hex.pm. So, I was use a `rebar3_hex` and in `*.src` file I put a `links` section like `{links, [{"Github", "https://github.com/NAME/PROJECT"}]},` and just push it into hex use plugin commands. In your case I do not see that you use any plugins. Maybe you need add [rebar3_hex](https://github.com/erlef/rebar3_hex) and use it for publishing?

**Comment by etnt** [comment]
I think I just followed this description:

https://rebar3.org/docs/package_management/

**Comment by etnt** [comment]
Ok I found it. 
I have added a Github link in the .app.src file.
