### ISSUE TITLE
Implementing tacacs_plus client

### ISSUE THREAD

**Issue by vkatsuba** [etnt/etacacs_plus#4]
Based on README description there is provided link to Python client https://github.com/ansible/tacacs_plus - at the same time in current project missed a common tests https://github.com/etnt/etacacs_plus/issues/2. It make sense to create client and provide as part of current project and use this client to build common tests.

**Comment by etnt** [comment]
Yes, a client would be nice. But I think it is valuable to test the server
with a different SW implementation of the protocol. This way, any
potential interop problems will be found.
