### ISSUE TITLE
Add GitHub actions

### ISSUE THREAD

**Issue by vkatsuba** [etnt/etacacs_plus#5]
Add simple CI for build and test project.

**Comment by etnt** [comment]
Fixed!
There are now two workflows:
1. One for OTP-21 to OTP-24 using rebar3-3.14.3
2. One for OTP-25 and later using rebar3-3.22.1

**Comment by vkatsuba** [comment]
The main issue with this CI
1 - it complex
2 - used GH component what has some issue - some of them, it not build OTP with SCTP flag, at least I has a problem when was try use it for Diameter application
Provided fixes/improvements https://github.com/etnt/etacacs_plus/pull/9

**Comment by vkatsuba** [comment]
And latest version if component is `4` for `actions/checkout` - https://github.com/actions/checkout/releases/tag/v4.1.1
