### ISSUE TITLE
Missing information about OTP versions

### ISSUE THREAD

**Issue by vkatsuba** [etnt/etacacs_plus#8]
Missed info about minimum OTP versions, and which OTP versions are supported. It can be add to README and/or `rebar.config` and also proof in GitHub actions in matrix level.

**Comment by etnt** [comment]
Fixed, added build dependencies to the README.
As soon as there exist tests we'll now if this is true
also when running the code.

**Comment by vkatsuba** [comment]
Cool! There was missed some point - it need to use `%` for comments in Erlang code block - fixed at https://github.com/etnt/etacacs_plus/pull/9

**Comment by vkatsuba** [comment]
Oh.. wrong ticket - but for this issue was added minimum OTP version in rebar config level
